### ISSUE TITLE
Login form to use username instead of email

### ISSUE THREAD

**Issue by renoirb** [webplatform/fxa-content-server#3]
Many layers are impacted. Solution might be to create an alternate login workflow beside the existing (i.e. inherit existing and overload).

**Comment by tilgovi** [comment]
Seems like the kind of thing we should push on upstream for, no?

**Comment by tilgovi** [comment]
I'd rather not see development that goes that deep happen in a fork.

**Comment by renoirb** [comment]
I doubt the Mozilla FxA team will.  They said its "by design" that they ask the user email to login. I got requests from my managers to use username instead.

**Comment by tilgovi** [comment]
Can we push back? Do they understand that it's probably _a lot_ of work?

**Comment by tilgovi** [comment]
And if upstream has no interest then it's even more work to do it modularly?

**Comment by renoirb** [comment]
Duplicate of #1
